$ANSIBLE_VAULT;1.1;AES256
62313631336361666635626239316462633164353561616635666534373764333066356130393333
3837306631623562613266616366383738613862363861310a366662363637363234303933306536
32333230363965343434326230616561336334663439623362626666363134643333346566663439
6465306536613131640a623735616231316362366432333739646532643430333734623037336261
64623238373066376632323664313964353731333261316431663130323234643331626663376139
39323639343732326231363438376136363432636638356262633532643033633237663833666432
64633431346138616132393935333134626634323064663639633666313266646433613664363665
66646433376233613962666530326139396238383831656363346631663734653838386464373133
39626632646638363834306436313866353637393061653930386339613336626362
